name: Generate CSV Daily

on:
  schedule:
    - cron: '0 1 * * *'  # 毎日 午前10時(JST)
  workflow_dispatch:  # 手動実行も可能

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run script
      run: python stock_csv_generator.py
   
    - name: Install dependencies
      run: pip install -r requirements.txt

      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
