name: Update stock sheet

on:
  schedule:
    - cron: '0 0 * * *'  # JST 9:00 に対応（UTC 0:00）
  workflow_dispatch:     # 手動実行も可

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v3

    - name: Pythonをセットアップ
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: 必要なライブラリをインストール
      run: |
        pip install yfinance gspread oauth2client ta pandas

    - name: スクリプトを実行
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        python stock_csv_generator.py
