name: Generate stock.csv

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # Pythonセットアップ
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 必要ライブラリをインストール
      - name: Install dependencies
        run: |
          pip install yfinance pandas

      # Pythonスクリプトを実行
      - name: Run Python script
        run: python stock_csv_generator.py

      # CSVファイルをコミット＆プッシュ
      - name: Commit and push CSV
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add stock.csv
          git commit -m "Add generated stock.csv"
          git push


