name: Generate CSV Daily

on:
  schedule:
    - cron: '0 1 * * *'  # 毎日午前10時(JST)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install yfinance pandas gspread oauth2client

    - name: Run script
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: python stock_csv_generator.py

    - name: Commit updated CSV
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add stock.csv
        git commit -m "Update stock.csv"
        git push



